////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Documentation

The latest released version:

* link:releases/content/1.11.0/FlumeUserGuide.html[Flume User Guide]
* link:releases/content/1.11.0/FlumeDeveloperGuide.html[Flume Developer Guide]

The documents below are the very most recent versions of the documentation and may contain features that have not
been released.

*  (unreleased version on github)
*  (unreleased version on github)

For documentation on released versions of Flume, please see the link:releases/[Releases] page.

FlumeUserGuide
FlumeDeveloperGuide
