////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Download

Apache Flume is distributed under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache License&#44; version 2.0]

The link in the Mirrors column should display a list of available mirrors with a default selection based on your
inferred location. If you do not see that page, try a different browser. The checksum and signature are links to the
originals on the main distribution server.

[cols=",,,",]
|===
|Apache Flume binary (tar.gz) |https://www.apache.org/dyn/closer.lua/flume/1.11.0/apache-flume-1.11.0-bin.tar.gz[apache-flume-1.11.0-bin.tar.gz] |https://www.apache.org/dist/flume/1.11.0/apache-flume-1.11.0-bin.tar.gz.sha512[apache-flume-1.11.0-bin.tar.gz.sha512] |https://www.apache.org/dist/flume/1.11.0/apache-flume-1.11.0-bin.tar.gz.asc[apache-flume-1.11.0-bin.tar.gz.asc]
|Apache Flume source (tar.gz) |https://www.apache.org/dyn/closer.lua/flume/1.11.0/apache-flume-1.11.0-src.tar.gz[apache-flume-1.11.0-src.tar.gz] |https://www.apache.org/dist/flume/1.11.0/apache-flume-1.11.0-src.tar.gz.sha512[apache-flume-1.11.0-src.tar.gz.sha512] |https://www.apache.org/dist/flume/1.11.0/apache-flume-1.11.0-src.tar.gz.asc[apache-flume-1.11.0-src.tar.gz.asc]
|===

It is essential that you verify the integrity of the downloaded files using the PGP or SHA512 signatures. Please read
https://httpd.apache.org/dev/verification.html[Verifying Apache HTTP Server Releases] for more information on
why you should verify our releases.

The PGP signatures can be verified using PGP or GPG. First download the https://www.apache.org/dist/flume/KEYS[KEYS]
as well as the asc signature file for the relevant distribution. Make sure you get these files from the
https://www.apache.org/dist/flume/[main distribution directory] rather than from a mirror.
Then verify the signatures using:

....
% gpg --import KEYS
% gpg --verify apache-flume-1.11.0-src.tar.gz.asc
....

Apache Flume 1.11.0 is signed by Ralph Goers B3D8E1BA

In addition, you can verify the SHA512 checksum on the files. A Unix program called sha or sha512sum is included in
many Unix distributions. Note that verifying the checksum is unnecessary if the PGP signature has been validated.

*Previous++_++Releases*

All previous releases of Apache Flume can be found in the https://archive.apache.org/dist/flume[archive repository].
