////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Team

A successful project requires many people to play many different roles.
Some write code or documentation, while others test releases, report problems, or contribute patches and ideas.
All contributions are greatly appreciated, and you can xref:getinvolved.adoc[get involved] today.

Apache Flume has been maintained by the
https://logging.apache.org/[Apache Logging Services] project
since March 2024, when the Apache Flume Project Management Committee (PMC) was dissolved and Logging Services adopted the project.
The current maintainers are listed on the
https://logging.apache.org/team-list.html[Apache Logging Services team] page.

== Contributors

A hand-curated list of contributors is never complete, and someone always ends up omitted unintentionally.
For this reason we do *not* maintain an official list of contributors:
the Git history is the authoritative record, and only the exceptions are listed below.

To see the full list of contributors, run the following command on a clone of the
https://github.com/apache/logging-flume[source repository]:

[source,bash]
----
git shortlog --summary --numbered
----

or browse
https://github.com/apache/logging-flume/graphs/contributors[the list computed by GitHub].

As usual, praise should go to these people, while blame should go to the
https://logging.apache.org/team-list.html[current maintainers].

The individuals mentioned below are the exceptions:
those who climbed higher on the
https://community.apache.org/contributor-ladder.html[ASF contributor ladder]
and those whose contributions are not recorded in the Git history.

=== Apache Flume PMC (2012-2024)

Apache Flume became a top-level Apache project in June 2012 and was governed by its own PMC until March 2024.

[NOTE]
====
Names marked with an asterisk (*) will not appear in the contributor lists generated from the Git history.
====

When Apache Logging Services adopted the project, the following PMC members joined the Logging Services team
and are listed on its
https://logging.apache.org/team-list.html[team page]:

* Bessenyei Balázs Donát (`bessbd`), the last chair of the Apache Flume PMC
* Juhani Connolly (`juhanic`)
* Mike Percy (`mpercy`)
* Ralph Goers (`rgoers`)
* Tristan Stevens (`tristan`)

The remaining PMC members retired together with the Apache Flume PMC:

* Aaron Kimball (`kimballa`) *
* Ahmed Radwan (`ahmed`) *
* Andrew Bayer (`abayer`)
* Arvind Prabhakar (`arvind`)
* Brock Noland (`brock`)
* Bruce Mitchener (`brucem`) *
* Denes Arvay (`denes`)
* Derek Deeter (`ddeeter`) *
* Eric Sammer (`esammer`)
* Ferenc Szabo (`szaboferee`)
* Hari Shreedharan (`hshreedharan`)
* Henry Robinson (`henry`) *
* Jaroslav "Jarcec" Cecho (`jarcec`)
* Jonathan Hsieh (`jmhsieh`)
* Mingjie Lai (`mlai`)
* Nick Verbeck (`nerdynick`) *
* Patrick Hunt (`phunt`) *
* Prasad Mujumdar (`prasadm`)
* Roshan Naik (`roshannaik`)
* Will McQueen (`will`)

The same applies to the following committers:

* Ashish Paliwal (`apaliwal`)
* Attila Simon (`sati`)
* Jeff Holoman (`jholoman`)
* Johny Rufus (`johnyrufus`)
* Mubarak Seyed (`mubarak`)
* Patrick Wendell (`pwendell`) *
* Sean Busbey (`busbey`)
* Wolfgang Hoschek (`whoschek`) *

=== Contributors of the pre-Apache and Incubator era

Flume was created at Cloudera in 2009 and entered the Apache Incubator in June 2011.

[NOTE]
====
Due to the process used to migrate the project history from SVN to Git,
the contributions of that era are credited in `From:` lines of the commit messages instead of the Git authorship metadata.
The contributors below therefore do not appear in the contributor lists generated from the Git history.
====

Besides the committers listed above, the following individuals contributed patches during that era:

* Abhinay Mehta
* Alejandro Abdelnur
* Alex Baranau
* Anurag Phadke
* Cameron Gandevia
* Chetan Sarva
* Dani Rayan
* David Arthur
* David Zuelke
* Dmitriy Ryaboy
* Harsh J
* Jacob Rideout
* Mark Chadwick
* Satish (`seerpini`)
* Todd Lipcon
* Tom White
* Vibhor Bhatt
* `newalex`
