staging:
  profile: ~
  whoami: trunk-site-stg-out
  subdir: content/flume/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 25467
# - Commit ID: 9b5f6ba1e66daf34809f549d29b7801c3c19bbe1
# - Timestamp: 2026-09-17T17:40:13Z
