staging:
  profile: ~
  whoami: trunk-site-stg-out
  subdir: content/flume/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 7960
# - Commit ID: e850a828040060d897bea6b0cb460237f3bd69ec
# - Timestamp: 2026-07-22T18:29:21Z
