staging:
  profile: ~
  whoami: trunk-site-stg-out
  subdir: content/flume/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 12498
# - Commit ID: 0005055b3db1ad5f4b7fce4cbafd128c66b00d26
# - Timestamp: 2026-07-22T18:23:16Z
