////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Version 1.10.1

*Status of this release*

Apache Flume 1.10.1 is the next release of Flume as an Apache top-level project
(TLP). Apache Flume 1.10.1 is production-ready software.

*Release Documentation*

* link:content/1.10.1/FlumeUserGuide.html[Flume 1.10.1 User Guide] (also in link:content/1.10.1/FlumeUserGuide.pdf[pdf])
* link:content/1.10.1/FlumeDeveloperGuide.html[Flume 1.10.1 Developer Guide] (also in link:content/1.10.1/FlumeDeveloperGuide.pdf[pdf])
* link:content/1.10.1/apidocs/index.html[Flume 1.10.1 API Documentation]

*Changes*

Release Notes - Flume - Version v1.10.1

++**++ Bug::
  * ++[++https://issues.apache.org/jira/browse/FLUME-3428[FLUME-3428]++]++ - Fix for CVE-2022-34916, improper use of JNDI in JMSMessageConsumer
  * ++[++https://issues.apache.org/jira/browse/FLUME-3434[FLUME-3434]++]++ - TwitterSource exceptions on serialization
++**++ Improvement::
  * ++[++https://issues.apache.org/jira/browse/FLUME-3427[FLUME-3427]++]++ - Add support for JPMS
  * ++[++https://issues.apache.org/jira/browse/FLUME-3433[FLUME-3433]++]++ - Limit the default Lookups to a specific few
