////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Version 1.11.0

*Status of this release*

Apache Flume 1.11.0 is the next release of Flume as an Apache top-level project
(TLP). Apache Flume 1.11.0 is production-ready software.

*Release Documentation*

* link:content/1.10.1/FlumeUserGuide.html[Flume 1.11.0 User Guide] (also in link:content/1.11.0/FlumeUserGuide.pdf[pdf])
* link:content/1.11.0/FlumeDeveloperGuide.html[Flume 1.11.0 Developer Guide] (also in link:content/1.11.0/FlumeDeveloperGuide.pdf[pdf])
* link:content/1.11.0/apidocs/index.html[Flume 1.11.0 API Documentation]

*Changes*

Release Notes - Flume - Version v1.11.0

++**++ Bug::
  * ++[++FLUME-3315++]++ - ++[++KafkaSink++][++KafkaSource++]++ Impossible to disable hostname verification with SSL enryption
  * ++[++FLUME-3437++]++ - Validate providerUrl
++**++ New Feature::
  * ++[++FLUME-3440++]++ - Add support for Spring Boot
++**++ Improvement::
  * ++[++FLUME-3435++]++ - Allow KafkaSink to include timestamp and KafkaHeaders
++**++ Dependency upgrade::
  * {blank}
  +
  ++[++FLUME-3441++]++ - Dependency Upgrades for Flume 1.11.0;;
    ** Update Maven Jar Plugin to 3.2.2
    ** Update Scala library to 2.13.9
    ** Update Gson to 2.9.1
