////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Apache Flume Spring Boot Source Repository

*Overview*

This project uses http://git-scm.com/[Git] to manage its source code. Instructions on
Git use can be found in the http://git-scm.com/documentation/[Git documentation].

*Web Access*

The following is a link to the online source repository.

*Anonymous Access*

The source can be checked out anonymously from git with this command::

....
$ git clone https://github.com/apache/flume-spring-boot.git
....

*Developer Access*

Everyone can access the Git repository via HTTP, but Committers must clone the git repository via HTTPS.:

....
$ git clone git@github.com:apache/flume-spring-boot.git
....

Committers should first commit the patch to trunk on your local repo:

....
$ git pull
$ git commit -m "A message"
$ git log
....

Copy the commit hash of the commit you just made. Then:

....
$ git pull
$ git cherry-pick <commit hash of the commit you made> (This should get committed immediately).
....

Now push to trunk:

....
$ git push -u origin trunk
....

For more details, please read: https://gitbox.apache.org/[Git at Apache].

Please note that the main development branch is *trunk*, not master.

*Access Through a Proxy*

The Git client can go through a proxy, if you configure it to do so. To configure git to use a proxy:

....
$ git config http.proxy address:port
....

Then do a git clone as usual:

....
$ git clone https://github.com/apache/flume-spring-boot
....

*Note 2:* Committers could use either Apache Gitbox or Github repositories. SVN can no longer be used to commit.
